module.exports = function (context, data) {
    if (data.method === "GET") {
        context.res = {
            body: {
                "response": "I live again."
            }
        };
    } else if (data.method === "POST") {
        context.log(data);
        context.log('Melisko webhook was triggered!');

        let wordsOfWisdom = [
            "Vedro tabaku prejebe za týždeň, ty kurva tuberácka",
            "Ja budem maluvať!",
            "Jebem boha",
            "Kurva, banda vyjebaná, čierna, špinavá.",
            "Čo sa toto naučili, zápalky pchát do dverí! No jebem im boha vyjebaného! No počkajte!!!! Tak zápalky budú pchát do zámkov.Ach, jebem ja vášho boha vyjebaného.No však počkaj, vy dvere neotvoríte.Vy dvere neotvoríte, pôjdete cez okno.",
            "Mne je jedno, ja odsedím v base do smrti.",
            "Ja zoberem hinto a im zapálim dvere, ten benzín.A zhoria zaživa tam.Ja zoberem ten benzín a zhoria.",
            "Pojdem zavolat 158, že som ich podpáliu.",
            "O tretej v noci ich podlejem benzínom, zhoria.",
            "Mne je to jedno, ja mám benzín pripravený.Ja ich oblejem, pooblievam a pôjdú do piči.",
            "Hned zajtra idem žandárom povedať, že tu príde tragédia, aby vedeli.",
            "Ty leňoch vyjebaný",
            "Ja viem čo je tomu (budíku), to je dojebané.",
            "To sa dejú veci tuto, s primitívma.",
            "Ja jebnem plyn, vyjebem celý dom do piči!!",
            "A bude ti do mňa jebať - kurva špinavá, špina skurvená - bude do mňa jebať !!!",
            "Ty trúba bláznivá, jebnutá",
            "Šedesiat korún stojí tuk!",
            "Budík zvoní, Miško spieva!",
            "Ty čo húkaš ty kurva tam!!!",
            "Ukáž mi tú minútu!",
            "Pozri sa, aha, šetko padá brizolit, to ani hodiny sa nedajú odpisuvať, čo jej voda kvápe.",
            "Od októbra vodu nedala spraviť!",
            "ja budem len hajzel malúvať, najebaná špina",
            "Šak keď voda tečie, tu sa jebú, kotia dole.",
            "To už mám dneska v piči celý deň, v piči!",
            "Šak nevadí, ja prejebem tisíc korún, mne je to jedno!!! Budeš mať piču, ty debil čierny, olašský.",
            "Halušky krupicové! Ty zebra!",
            "Etela! Indiánka negramotná! Hotovo!",
            "Téé, ale vtáčik",
            "Boha Mária špinavého.",
            "Ale papriky nosí, jebe rajčiny furt, hnilé všelijaké.",
            "Už má peniaze, už je jebnutá!!",
            "Herodes vyjebaný",
            "...zas tam dala tú kapustu...",
            "Ále čo robíš, a čo ti jebé??? Boha a čo padlo dole?",
            "Ja nevjem čo padlo dole...",
            "Vodu nevládze vtákovi dať, ale do obchodu to devať rázy pojde!!",
            "Áchab!",
            "Ale od rána jebe bubny, kokot, debil vyjebaný, debilský.Ja si televízor zoberem a pojdem na rieku Nitru pozerať, skrz kokota vyjebaného.Skurveného.",
            "Pozri sa, aha, mravce chodia po byte! Sa tam honia...",
            "Ja pôjdem do tej izby a rozjebem celý byt!",
            "Ach, jebem ja vášho boha!",
            "Boha, ešte som nedopo... kde to dam, ano!",
            "Jebem ja tvojho kurvu materinu vyjebanú",
            "A to skrz tú piču.Lebo som zhasou a som sa potkou.",
            "Ja zavolám mestských policajtov, ja idem na oné, normálne idem na poštu a zavolám 158, policajtov mestských",
            "Neni doma? Však bude doma!",
            "Do to vypau?! A to kto podpísal?",
            "Tri roky chodil na doučuvanie, už nie.Lebo už je deviatak, už má... všetko vie!",
            "Človek maluje, ona rozjebe!",
            "To čo si najebala na mňa? Akú habaďúru? Ty sviňa!",
            "Už si sa nažrau, Mišulko ?",
            "Ja som král Šumavy",
            "Ty bzdocha vyjebaná",
            "Do papuče ma voláááá... opitého kokota.Ty kurva najebaná, cigánska",
            "Skurvená, kuplerajská, vyjebaná, špinavá, kurviacka skurva, vyjebaná sviňa! Ale cibulu byte nemá!",
            "Čo máš... Ba v onom, piču ?",
            "Ty harfa najebaná, harfatá",
            "Ty Herodes vyjebaný",
            "Ty zmoknutá kurva, ty zmoknutá kurva čierna",
            "Ty osemkilová kurva špinavá čierna.Hrbatá svinská.Chinguľa vyjebaná.",
            "Ty múmia vyjebaná skurvená mumácka",
            "Ty kurviacká skurva",
            "Ty kurva špinavá, neandertálska, cigánska, primitívska, prašivá",
            "Ty špina buzerantská, čierna, skurvená, ty sviňa orangutánska, olašská, špinavá, ty špina bosorácká, kurva najebaná",
            "Ja ju zabijem v noci! Tí zhoria!",
            "Pôjdú do piče odtiaľto!",
            "Celý činžák bude hore pičou.",
            "Kde mám dať pásku?",
            "Hodiny sa zajebané, celé čo voda kvápe! Šak to sa ani odpisuvať nedá!",
            "Máme doma Cigáňov byte.Tfuj!!",
            "Čože ? !Ju zujíma víno!!!",
            "Etela! Boha, jebnem po tebe volačo!",
            "Aj cukor v piči, aj čerešne, po strome sa jebem, zaváram!",
            "Lebo němôžme jesť, nemáme cibuľu!",
            "Aj oné...keksy",
            "To tomu neveríš, že keď ja pôjdem do izby, že rozjebem celý byt?",
            "Ale na kurvy to má...na to má...na to má, vyjebané kupúvať.",
            "Aha, mravce chodia tadeto od Šarinov hore... hore, dole, ako chcú",
            "Vo vlastnom byte si nos rozjebem.",
            "Už mám bachor v kokote.Nebolel ma od rána a ked prídem tu, do tohto skurveného bytu, už som v piči.",
            "Skur... Sypali sa orechy z toho smetiaka, čo bol kopcom!",
            "Vyjebany mozog, ...vyjebany mozog, ...",
            "Daj mi cibulu, cibulu mi daj!",
            "Jebem já vášho boha vyjebaného, čo vy se mňu tu robíte.",
            "Kurva ja dám každému pokoj a tu ti len do prieku robia furt!!! Jebem im boha vyjebaného!",
            "Ty herbra vyjebaná!",
            "Jebem orechy! V teplákoch ako kokot.",
            "Včil išla pre peňáze, keď najviac jebe!",
            "Sem póóóď!",
            "Ach, ...ty churva...",
            "Ty mahagárska kurva špinavá.",
            "No počkaj, ja ti dám tenis, aj Šarinov.",
            "Neškriekaj, keď som na chodbe!!! Lebo ťa zajebem.",
            "Syna mááám a s cigáňma hrá tenis.No dobre si dopadol, ty kokot!",
            "To čo si najebala na mňa akú habaďúru?",
            "Ja si môžem akurát tak dať konský kokot a nie dve palacinky.",
            "Čo si mám dať na ten nos, kokot ?",
            "Celé ruky mám krvavé, aha.",
            "A teraz si piču rozjebem ja.",
            "Komu tykáš?",
            "Ona varí doma v byte... ŠPINA VYJEBANÁ! KOMU VARÍŠ?",
            "Čo varíš? Materinu piču varíš?",
            "Pletenku suchú žerem! Pletenku žerem na večeru, aha! Pletenku! Čo chodím na verejno prospešné práce, tak žerem pletenku na večeru, suchú.",
            "Ja najebem celému činžáku",
            "Desať dní nežerem a toto mi dá na večeru! Kožuch zo zavináča!",
            "Hinten pahliak vyjebaný pahliacky.",
            "Špina najebaná, ťa zabijem tu!",
            "Ja sa ťa pýtam, či budeš s hríbama volačo...",
            "Tak ja budem televízor plaťiť sto korún, ešte aj satelit deväťdesiat a televízor mi nejde! ? Jebem ja vašu piču...",
            "Ty cigánska kurva! Si mi povedala zhasni a ja som sa potkou.",
            "nehuč!!!!!!!!!!!! TY SVIŇA.",
            "Boha, daj tu vázu materi do piče, lebo ťa zabijem!",
            "Čože! Ten zožere aj smrtke piču!!!!",
            "Ona poví božemój...",
            "To si daj ty, ja nechcem nič.Lebo ja som notorický alkoholik!",
            "Toto Mária kurva nedá dokopy...",
            "Čerešne!",
            "Čo tam ta kurva húka. (Škrieka)Ty čo húkaš ty kurva tam!",
            "Boha, všetky taniere som prejebal.",
            "No toto je v piči!",
            "Čo robia tí blázni? Čo im JEBE?",
            "A mne poví, že bože mój.Ani slovo som jej nepovedau.Tu sedím a driemem.A ona mi poví, že bože mój.BOŽE MÓJ? !TY SVIŇA!!",
            "Aha, rozjebala celé dvere.",
            "Však sa otvorí dvere, odpande ten spodný pant a môžete isť do piči... materi.",
            "Tu sa maluje, dojebe sa vodovod, tam sa maluje, dojebe sa ľadnička, tu sa maluje, rozjebe taniere!!",
            "Ty jurisa vyjebaná.",
            "Ťa prejebem nožom 250 rázy.",
            "Mám zas nervy dostať? Volakoho tu zajebem.",
            "Mu hlavu takto chytím, mu ju jebnem a mu väzy odtrhnem, kokotovi.",
            "Stiahnem ho sem do vnútra, ho jebnem do vreca a jebnem ho do rieky Nitry.",
            "Stôl rozbitý, ľadnička rozbitá, hinto rozjebané, dvere všetky rozjebané.",
            "Lebo začnem jebať po tej rúre, celý činžák bude hore pičou!",
            "Kurva, vy zhoríte do rána.",
            "Ja ich v noci podpálim, zhoria!",
            "Zle dopadnú hinte svine.Uvidíš, čo ja spravím... v noci.",
            "Pol hodiny som ticho.",
            "Tí zhoria zaživa... v tom byte.",
            "Ja len zámky mením, ale oni si budú hlavy meniť.Keď prídem najebaný raz.",
            "Ja donesem ty granáty dva a hotovo.A benzín.A pôjdú do piče.",
            "Ja ich ojebem kyselinou.",
            "Špiny galantské, vyjebané, skurvené.",
            "Už to dala tichšie zas, tá sviňa vyjebaná, skurvená špina.Toto ona robí furt.",
            "Primitívi negramotní, vyjebaní, špinaví, hluchí, najebaní.Pod oknom ti bude sedet tá kurva hluchá, vyjebaná.",
            "Však oni budú mať otvorené... hlavy.",
            "Tretiu vložku, čo rozjebali.Špiny vyjebané.",
            "Nevyjdú z domu.Buď zhoria, alebo nevyjdú z domu.",
            "Ja som šéf!",
            "Ťa tu zajebem tým nožom, ani materina kurva ťa tu nenájde.Peter príde domov, nájde ťa tu zajebanú.",
            "Ty chceš aby som zle spraveu?",
            "Ja mám aj na hríby, aj rezať aj zavárať...aj piču.A on nevie kde má vtákovi vodu dať.",
            "A to mi Hendžo dal, že pre mňa, to je dvojročná, mäkká feferónka.Pozri, aj tu zožrala.",
            "Žraloci skurvení, vyjebaní, zožerú celý byt.Feferónky mäkké, dvojročné na Vianoce.",
            "No počkaj, kúpiš si cigarety...či tabak...ale ťa zabijem",
            "No aby volakto sol nemal byte? Ježišmárja",
            "Išiel? A kde išiel? Po Bojnickej ceste budík išiel?",
            "Ty zomieraš, tebe jebe",
            "Vstávaj Honzo hore, na bani klopajú, ak neskoro prídeš, fárať ti nedajú!",
            "Ale sa jebúú, honia sa, voda kvápe! Ja budem malúvať!",
            "Bola si doma? Búúúchali ??",
            "Potreby kúpim...Ale žiadne obleky ja mu kupúvať nebudem!",
            "Žena v domácnosti nemá cibulu.No teda Hendžo je kokot dôchodca starý, ale toto sa u neho nemôže stať.To len u takejto špiny vyjebanej, skurvenej.",
            "Špina zákerná, čo nedopraje druhému ani KOKOT!!!",
            "Piča Ranná krava",
            "Jebem orechy!",
            "No jebem ja vášho kokota",
            "To ja mám zas nervy dostať? Volakoho tu zajebem?",
            "Ja ho zabijem tam pri tých dverách, trest smrti neni, tak budem doživotne v onom...v base.Ale ho zabijem tam pri tých dverách.",
            "Bachor ma nebolel od rána.TY SVIŇAAAAA!!!",
            "Už mám bachor v kokote",
            "Ty chinguľa osemkilová, špinavá svina",
            "Do koša kukajú, čo nosím... jablká... im oné zuby jebú.Špinám lenivým, skurveným, negramotným.",
            "Ej, ale vy dvere neotvoríte ráno! Jebem ja vašu mater, kurvu vyjebanú! Jebem ja vášho boha! Ah, vy svine skurvené!",
            "Kurva, ja som ticho!",
            "Ten zožere aj smrťke piču",
            "Ach, ty čierna piča",
            "Jebem mu kurvu vyjebanú!!",
            "Nevadí, ja mám 54 rokov, ale vy doplatíte, vy doplatíte namňa!!",
            "Ty flandra najebaná, zdochliacka kurva, špinavá, vyjebaná! Ale spí furt, kurva, špinavá, spí furt, spí, sviňa!",
            "Šak sa dosmeješ, keď ti voľačo jebnem do hlavy!!!",
            "Kurva, na teba je škoda aj náboj!",
            "Ja pijem, aby som nežral!",
            "Čo je jebnutý? !Alebo je hluchý, kokot!!",
            "Čo je v cirkuse? Šak býva v činžáku!",
            "Kurva, ráno kríky strihám, nikoho si nevšímam, v piči som, prídem domov ja nemôžem televízor kukať!",
            "Čo má tlmiče v ušiach?!",
            "A bude ti naprotiveň jebať!",
            "V škole žere a ešte aj z toho, čo mám ja žrať, aj to zožere!",
            "Všetko jebe za jazdy, aby mohol srať potom, grcať...tak žere.",
            "Oni žerú ako svine!! Ako prasce na druzstve!!!",
            "Počkaj, keď toto ja zajtra poviem v krčme...",
            "POJEB MA!!! NECHCEM NIČ!!!!!",
            "PRIDEŠ SEM TA ZABIJEM!!!",
            "ČO ROBÍŠ?! ČO TI UŽ JEBE?!?!",
            "Že ju nevie roztrhnúť, alebo autom zabiť, alebo kju mater kurvu.",
            "Opitý som? Opitý som! Áno, som.Ja som najebaný ako...5 dní som najebaný, napitý...4, 9 promile celý týždeň.",
            "Aby ťa mater zabila!!!",
            "JA TI POVIEM KOKOT VYJEBANÝ!!!!!!! ŽRALOCI VYJEBANÍ!!! CELÝ BYT ZOŽERÚ!!!",
            "No a kedy to žrala? Potajme musela, keď som neni doma.",
            "A to sa nebála otvoriť? (feferónky)",
            "Ty debil čierny, olašský!",
            "Už mám nervy v piči zas!!",
            "Aha, čo mi dala na večeru...jak bezdo..Bezdomovcovi mi dala žrať!",
            "Ja s cigáňma nerobím",
            "De máš s tyma páskama tie modré gate!",
            "Kurva, že ju nevie rozdrapiť voľade.",
            "Dobošky a pagáče všelijaké makové, to kupuje!",
            "Že aha? Že aha! Aha!",
            "No toto je MARHA!",
            "Ja mám 54 rokov, ale vy doplatíte na to",
            "Ty špina vyjebaná!... Ty kurva sopliacka!... Čo ti už ozaj jebe? Ty múmia zasraná, vyjebaná, skurvená!... Ti odjebem hlavu, ty kurva!",
            "Všetko tu rozjebem...všetko.VŠETKO!!! Aj tie poháre jebnuté.A potom aj tvoju hlavu negramotnú rozkurvím.Len ma jeb...",
            "TU SOM MAL 500 KORÚN!!!",
            "Chytím ich vyjebem do kontajnera...všeckých!",
            "POJEB MA! NECHCEM NIČ!",
            "BOHA, DESIATY RAZ MA VYTOPILI!",
            "A žere, šecko požere...jak prasce na družstve!",
            "ČO JEBEŠ ZAS? UŽ ZAS JEBEŠ? !KURVA JA SOM TICHO... TI BUDE NORMÁLNE JEBAŤ DO TEBA! TY ŠPINA!",
            "Tvoju čiernu piču!",
            "Miško toho budika sa nechytaj",
            "Ty kotná kurva!",
            "Tá debilka čo robí!!! KURVA lebo zajebem plyn, vyjebem celý dom do piči!"
        ];

        let randomWisdom = wordsOfWisdom[Math.floor(Math.random() * wordsOfWisdom.length)];

        context.log('Melisko webhook responded : ' + randomWisdom);

        context.res = {
            body: {
                "response_type": "in_channel",
                "text": randomWisdom
            }
        };
    }

    context.done();
}